server:
  port: 8130

aliyun:
  oss:
    endpoint: 
    keyId: 
    keySecret: 
    bucketName: 
spring:
  application:
    name: service.oss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.100:8848
