server:
  port: 8110
spring:
  datasource:
    url: jdbc:mysql://192.168.43.100:33306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: service-core
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.mapper
#  type-aliases-package: com.moshuanghao.pojo