server:
  port: 8110
spring:
  datasource:
    url: jdbc:mysql://192.168.43.100:33306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: service-core
  redis:
    host: 192.168.43.100
    port: 6379
    database: 0
    timeout: 3000ms
    jedis:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.100:8848
    sentinel:
      transport:
        dashboard: 192.168.43.100:8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.moshuanghao.pojo